"""FAISS-backed job retrieval using LangChain's vector-store integration."""
from __future__ import annotations

import json
from typing import Any

from langchain_community.vectorstores import FAISS
from langchain_community.vectorstores.utils import DistanceStrategy

from . import config
from .gemini import embeddings


class JobStore:
    def __init__(self) -> None:
        self.jobs: list[dict[str, Any]] = []
        self.vectorstore: FAISS | None = None
        self.load()

    @property
    def ready(self) -> bool:
        return bool(self.jobs) and self.vectorstore is not None

    def load(self) -> None:
        """Load the offline-built LangChain FAISS index and job metadata."""
        if not (config.FAISS_INDEX_PATH.exists() and config.FAISS_DOCSTORE_PATH.exists()):
            return
        try:
            # This artifact is generated by this application's trusted ingestion job.
            self.vectorstore = FAISS.load_local(
                str(config.DATA_DIR),
                embeddings(),
                index_name=config.FAISS_INDEX_NAME,
                allow_dangerous_deserialization=True,
                distance_strategy=DistanceStrategy.MAX_INNER_PRODUCT,
                normalize_L2=True,
            )
            if config.JOBS_PATH.exists():
                self.jobs = json.loads(config.JOBS_PATH.read_text(encoding="utf-8"))
            else:
                self.jobs = [
                    dict(document.metadata)
                    for document in self.vectorstore.docstore._dict.values()
                ]
        except Exception as exc:
            # A bad/mismatched local artifact should make health report not-ready,
            # rather than stopping the API from serving its diagnostic endpoint.
            print(f"WARN: could not load FAISS index: {exc}")
            self.vectorstore = None
            self.jobs = []

    def semantic_search(
        self, query_vec: list[float], *, top_k: int = 8, category: str | None = None
    ) -> list[dict[str, Any]]:
        """Return the same job dictionaries as before, with cosine similarity scores."""
        if not self.ready or self.vectorstore is None:
            return []

        filter_: dict[str, str] | None = {"category": category} if category else None
        # The FAISS index uses inner product over L2-normalized vectors, which is
        # cosine similarity.  fetch_k leaves enough candidates for a category filter.
        matches = self.vectorstore.similarity_search_with_score_by_vector(
            query_vec,
            k=top_k,
            filter=filter_,
            fetch_k=max(top_k * 5, 20),
        )
        return [
            {**dict(document.metadata), "score": round(float(score), 4)}
            for document, score in matches
        ]

    def lexical_search(self, query: str, *, top_k: int = 8) -> list[dict[str, Any]]:
        """Keyword fallback used when no API key is configured."""
        terms = [term for term in query.lower().split() if term]
        scored = []
        for job in self.jobs:
            haystack = " ".join(
                str(job.get(key, "")) for key in ("title", "company", "category", "summary")
            ).lower()
            hits = sum(haystack.count(term) for term in terms)
            if hits:
                scored.append({**job, "score": hits})
        scored.sort(key=lambda job: -job["score"])
        return scored[:top_k]

    def categories(self) -> list[str]:
        return sorted({job.get("category", "") for job in self.jobs if job.get("category")})
